version: '3.8'

services:
  bun:
    environment:
      - MONGO_USERNAME=mongouser
      - MONGO_PASSWORD=mongouserpass
      - MONGO_HOST=db
      - MONGO_PORT=27017
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bun
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongouserpass
      - MONGO_INITDB_DATABASE=trials
    ports:
      - "27015:27017"
    volumes:
      - data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
volumes:
  data: